### ISSUE TITLE
KeyError: 'seq_0' on Running Notebook with BindingDB_All_202404.tsv

### ISSUE THREAD

**Issue by fnyfauzi** [dangjaya/drugMCTS#2]
Hi, got error during running notebook

filterDF=filterDF[ (filterDF['seq_0'].str.len() > 80) & (filterDF['seq_0'].str.len() < 2050) ]
filterDF=filterDF[['can_smiles','seq_0','BindingDB Ligand Name','Target Name Assigned by Curator or DataSource','Target Source Organism According to Curator or DataSource','IC50 (nM)','Kd (nM)','EC50 (nM)']]
print ("Resulting dataframe  ", filterDF.shape)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File /root/miniconda3/envs/drugai/lib/python3.10/site-packages/pandas/core/indexes/base.py:3621, in Index.get_loc(self, key, method, tolerance)
   3620 try:
-> 3621     return self._engine.get_loc(casted_key)
   3622 except KeyError as err:

   3621     return self._engine.get_loc(casted_key)
   3622 except KeyError as err:
-> 3623     raise KeyError(key) from err
   3624 except TypeError:
   3625     # If we have a listlike key, _check_indexing_error will raise
   3626     #  InvalidIndexError. Otherwise we fall through and re-raise
   3627     #  the TypeError.
   3628     self._check_indexing_error(key)

KeyError: 'seq_0'

**Comment by Stamcini** [comment]
I seem to have found the key to this:
in the 6th cell of the notebook,
```python
df = df.reset_index()
df = df.rename(columns={'BindingDB Target Chain  Sequence.{}'.format(j): 'seq_{}'.format(j) for j in range(1,13)})
df = df.rename(columns={'BindingDB Target Chain  Sequence': 'seq_0'})
```
the columns that should have been renamed to 'seq_0' were not renamed, for the name of them were inserted with an extra SPACE between 'Chain' and 'Sequence'.
delete the extra SPACEs to fix it. this works for me(using BindingDB_All_202404.tsv)

**Comment by fnyfauzi** [comment]
yes, thank you, all works fine
